deploymenttheory/terraform-provider-microsoft365

README.md, internal/provider/datasources.go, internal/provider/provider.go, internal/provider/resources.go
=> Updated docs

internal/resources/devicemanagement/beta/assignmentFilters/helpers.go, internal/resources/devicemanagement/beta/assignmentFilters/object.go, internal/resources/devicemanagement/beta/assignmentFilters/resource.go, internal/resources/devicemanagement/beta/assignmentFilters/resource_model.json, internal/resources/devicemanagement/beta/assignmentFilters/state.go, internal/resources/devicemanagement/beta/assignmentFilters/validators.go
=> separated stating logic from read func

internal/resources/common/state.go, internal/resources/devicemanagement/beta/assignmentFilters/object.go, internal/resources/devicemanagement/beta/assignmentFilters/resource.go, internal/resources/devicemanagement/beta/assignmentFilters/state.go, internal/resources/devicemanagement/beta/assignmentFilters/validators.go
=> updated stating and resource construction functions for devicemanagement filters

go.mod, go.sum, internal/resources/devicemanagement/beta/assignmentFilters/resource.go
=> Added timeouts to device filters - intune

internal/constants/constants.go, internal/helpers/cert.go, internal/provider/authentication.go, internal/provider/provider.go, internal/provider/validators.go
=> added certificate validators and consts for various ms cloud types

internal/provider/authentication.go, internal/provider/provider.go
=> refactor for entraID auth workflow with client build options for all auth journey's. with proxy support

.github/workflows/documentation.yml, .github/workflows/linter.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/workflow.yml, examples/microsoft365_provider/provider.tf, internal/provider/provider.go
Add gha for doc gen that will run when PR into main
=> Added documentation generation github action

examples/microsoft365_graph_beta_device_and_app_management_assignment_filter/resource.tf, internal/helpers/variables.go, internal/provider/provider.go, internal/provider/resources.go, internal/provider/validators.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/helpers.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/object.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/resource.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/state.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/validators.go
=> Feature scaffolding - refactor for resource imports and validator functions

internal/provider/provider.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/resource.go, main.go
add debug logging throughout provider and main
add context in main
standardized logging behaviour
=> added debugging for provider

internal/helpers/conversion.go, internal/resources/common/construct.go, internal/resources/common/state.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/crud.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/state.go
=> Feature scaffolding - bug fixing stating of test resource

internal/provider/resources.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/resource.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/constructs.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/crud.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/resource.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/resource_model.json, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/state.go
Added resource schema, crud functions, object construction and stating capability
=> Feature scaffolding - added graph example - cloudpc provisioning profile

examples/microsoft365_graph_cloud_pc_provisioning_policy/resource.tf, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/resource.go
=> Feature scaffolding - added example

examples/microsoft365_graph_cloud_pc_provisioning_policy/README.md, examples/microsoft365_graph_cloud_pc_provisioning_policy/resource.tf, examples/microsoft365_provider/provider.tf, internal/helpers/cert.go, internal/helpers/variables.go, internal/provider/debug.go, internal/provider/entra.go, internal/provider/provider.go, internal/provider/validators.go
=> Feature scaffolding - bug fixing env vars and certificate auth

internal/helpers/cert.go, internal/helpers/cert_test.go, internal/helpers/conversion_test.go, internal/helpers/md5_test.go, internal/provider/cloud_test.go, internal/provider/entra.go, internal/provider/provider.go
=> Feature scaffolding - added client assertion (oidc) auth method to provider for testing

go.mod
This commit updates the go.mod file to include the testify v1.9.0 package as a direct dependency. This is necessary for the upcoming changes that will utilize the testify library for writing tests and asserting conditions. By explicitly adding the testify package, we ensure that the correct version is used and avoid any potential conflicts with indirect dependencies.
=> chore: Update go.mod to include testify v1.9.0

internal/provider/entra.go, internal/provider/provider.go
=> refactor: Remove unused code for obtaining Client Assertion Credential and added markdown docs

.github/workflows/test.yml, examples/main.tf
=> Feature scaffolding - bug fixes for test.yml pipeline

examples/README.md, internal/helpers/conversion.go, internal/helpers/conversion_test.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/state.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/construct.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/model.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/resource.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/resource_model.json, internal/resources/identityandaccess/beta/conditionalaccesspolicy/state.go
=> Feature graph beta conditional access - added constructor funcs and bud fixes for conditional access policy

examples/microsoft365_graph_beta/microsoft365_graph_beta_identity_and_access_conditional_access_policy/resource.tf
=> added conditional access policy example

.github/workflows/documentation.yml, examples/microsoft365_graph_beta/microsoft365_graph_beta_identity_and_access_conditional_access_policy/resource.tf
=> Feature graph beta conditional access

.github/workflows/documentation.yml
=> bug fix for file path in docs pipeline

.github/workflows/documentation.yml
=> Feature scaffolding - bug fixes for doc gen pipeline

.github/workflows/documentation.yml
=> chore: fixes for doc gen

.github/workflows/community_release.yml, .github/workflows/provider.yml, .github/workflows/release.yml
=> added maintainence pipelines

.github/workflows/linter.yml
=> bug fixx for linter pipeline fetch depth

.github/workflows/linter.yml
=> update for linter pipeline

.github/workflows/linter.yml, .markdown-lint.yml, internal/resources/common/state.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/crud.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/crud.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/crud.go
=> modified linting behaviour for markdown .md file exclusion

internal/resources/common/resource.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/resource.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/resource.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/resource.go
=> centralized graph and graph beta client configure functions with helper

.github/workflows/test.yml, .goreleaser.yaml
=> Feature scaffolding - removed non required arches from go releaser

.github/workflows/test.yml, .goreleaser.yaml
=> Feature scaffolding  - extended  pipeline run times for testing and refined arch release options for goreleaser

examples/README.md, examples/microsoft365_graph/microsoft365_graph_cloud_pc_user_setting/resource.tf, internal/resources/common/crud/error.go, internal/resources/common/crud/state.go, internal/resources/common/crud/timeout.go, internal/resources/common/crud/timeout_test.go, internal/resources/common/schema/timeouts.go, internal/resources/common/state/conversion.go, internal/resources/common/state/conversion_test.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/crud.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/resource.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/state.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/crud.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/resource.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/state.go, internal/resources/devicemanagement/v1.0/cloudPcUserSetting/crud.go, internal/resources/devicemanagement/v1.0/cloudPcUserSetting/resource.go, internal/resources/devicemanagement/v1.0/cloudPcUserSetting/state.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/crud.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/resource.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/state.go
=> moved conversion funcs for state from helpers to common > state

examples/README.md, examples/microsoft365_graph/microsoft365_graph_cloud_pc_device_image/resource.tf, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_assignment_filter/resource.tf, internal/datasources/deviceandappmanagement/beta/assignmentFilter/datasource.go, internal/datasources/deviceandappmanagement/beta/assignmentFilter/read.go, internal/datasources/devicemanagement/v1.0/cloudPcDeviceImage/datasource.go, internal/datasources/devicemanagement/v1.0/cloudPcDeviceImage/read.go, internal/resources/common/setclient.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/crud.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/resource.go, internal/resources/deviceandappmanagement/beta/assignmentFilter/state.go, internal/resources/devicemanagement/v1.0/cloudPcDeviceImage/crud.go, internal/resources/devicemanagement/v1.0/cloudPcDeviceImage/resource.go, internal/resources/devicemanagement/v1.0/cloudPcDeviceImage/state.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/crud.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/resource.go, internal/resources/devicemanagement/v1.0/cloudPcProvisioningPolicy/state.go, internal/resources/devicemanagement/v1.0/cloudPcUserSetting/crud.go, internal/resources/devicemanagement/v1.0/cloudPcUserSetting/resource.go, internal/resources/devicemanagement/v1.0/cloudPcUserSetting/state.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/crud.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/resource.go, internal/resources/identityandaccess/beta/conditionalaccesspolicy/state.go
=> Feature scaffolding - added data sources and refactored setclient function to support data sources

.github/workflows/release.yml, .github/workflows/test.yml
added path exclusions and upped time for test pipeline duration
=> Feature scaffolding bugfix - refinement for testing pipeline behaviour

.github/workflows/documentation.yml, .github/workflows/release.yml, .github/workflows/test.yml, examples/README.md
=> removed push from pipeline testing

.github/workflows/linter.yml, .github/workflows/release.yml, examples/README.md
=> Feature pipelines - Disable CPD (Copy Paste Detection) for all languages

.github/workflows/documentation.yml, .github/workflows/linter.yml, examples/README.md
=> Feature pipelines - chore: Update timeout minutes in linter workflow

.github/workflows/documentation.yml, .github/workflows/linter.yml
=> Feature pipelines - fixes for docs and linter pipelines

.github/workflows/test.yml
=> chore: Update go-version to stable for caching in test workflow

.github/workflows/test.yml
Disabling acceptance tests for the time being. will reinstate later
=> chore: disable acceptance tests in test workflow

internal/datasources/device_and_app_management/beta/assignment_filter/read.go, internal/provider/datasources.go
=> Feature pipelines

README.md, docs/providerroadmap/roadmap.md
=> chore: reorganized documentation

.github/workflows/documentation.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/test.yml
=> chore: Updated test and pr pipelines

.github/workflows/documentation.yml, .github/workflows/test.yml
=> Feat pipeline redesign

.github/workflows/community.yml, .github/workflows/release.yml
=> chore: Update goreleaser-release-args in terraform-provider-release job

.github/workflows/acceptance-tests.yml, .github/workflows/community.yml, .github/workflows/tests.yml
=> Bug fixes for test pipeline triggers

.github/workflows/community.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml
=> changed release pipelines to  ubuntu-24.04-4c.16gb

examples/microsoft365_graph/microsoft365_graph_device_and_app_management_role_definition/README.md, examples/microsoft365_graph/microsoft365_graph_device_and_app_management_role_definition/resource.tf, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_role_definition/README.md, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_role_definition/resource.tf, go.mod, go.sum, internal/resources/device_and_app_management/beta/role_definition/construct.go, internal/resources/device_and_app_management/beta/role_definition/crud.go, internal/resources/device_and_app_management/beta/role_definition/model.go, internal/resources/device_and_app_management/beta/role_definition/resource.go, internal/resources/device_and_app_management/beta/role_definition/resource_model.json, internal/resources/device_and_app_management/beta/role_definition/state.go, internal/resources/device_and_app_management/v1.0/role_definition/construct.go, internal/resources/device_and_app_management/v1.0/role_definition/crud.go, internal/resources/device_and_app_management/v1.0/role_definition/model.go, internal/resources/device_and_app_management/v1.0/role_definition/resource.go, internal/resources/device_and_app_management/v1.0/role_definition/resource_model.json, internal/resources/device_and_app_management/v1.0/role_definition/state.go
Added 2 new resources with examples
=> Feat: + microsoft365_graph_device_and_app_management_role_definition & microsoft365_graph_beta_device_and_app_management_role_definition

.github/workflows/permissions.yml
=> feat: update actions/upload-artifact version to v4.4.0

.github/workflows/permissions.yml
=> bug fixes for permissions pipeline workflow

go.mod, go.sum
=> Update go.mod and go.sum dependencies

.github/workflows/community.yml, .github/workflows/documentation.yml, .github/workflows/linter.yml, .github/workflows/permissions.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml
=> Feat: changed pipeline version to user symVar numbers rather than commits

internal/resources/common/utilities/utilities.go, internal/resources/device_and_app_management/beta/winget_app/crud.go, internal/resources/device_and_app_management/beta/winget_app/helpers.go, internal/resources/device_and_app_management/beta/winget_app/model.go, internal/resources/device_and_app_management/beta/winget_app/resource.go, internal/resources/device_and_app_management/beta/winget_app/state.go
=> Feat removed from winget_apps assignment logic to now use a dedicated tf resource for assignments.

internal/resources/device_and_app_management/beta/windows_settings_catalog/crud.go, internal/resources/device_and_app_management/beta/windows_settings_catalog/diff_suppression.go, internal/resources/device_and_app_management/beta/windows_settings_catalog/resource.go
added initial diff suppression logic
=> Feat windows settings catalog

.github/workflows/metadata-maintainence.yml
=> Feat intune settings templates

.github/workflows/metadata-maintainence.yml, templates/resources.md.tmpl
=> Fix for examples template and update to metadata pipeline pr comments

.github/workflows/documentation.yml, .github/workflows/linter.yml, .github/workflows/unit-tests.yml, templates/resources.md.tmpl
=> Feat added pipeline hardening step

.github/workflows/documentation.yml
=> Fix for documentation pipelines

.github/workflows/terraform-docs.yml
=> Add GitHub Actions bot user details for automated Terraform docs commits

internal/resources/common/normalize/settings_catalog.go, internal/resources/common/normalize/settings_catalog_test.go, scripts/GetSettingsCatalogConfigurationById.ps1
=> Refactored settings catalog export script to align with expected formatting within the HCL + added secret value test suite

.github/workflows/auto-merge-dependabot.yml, .github/workflows/dependancy-review.yml, .github/workflows/pr-branch-name-check.yml
=> Feat-added new gha's for dependabot automerge and dependancy reviews

.github/workflows/auto-merge-dependabot.yml
=> Add condition to auto-merge workflow for Dependabot bot

.github/workflows/auto-merge-dependabot.yml, .github/workflows/dependancy-review.yml, .github/workflows/go-docs.yml, .github/workflows/linter.yml, .github/workflows/metadata-maintainence.yml, .github/workflows/pr-branch-name-check.yml, .github/workflows/release.yml, .github/workflows/unit-tests.yml
=> Feat endpoint priv management

examples/microsoft365_graph/microsoft365_graph_device_and_app_management_cloud_pc_user_setting/resource.tf, examples/microsoft365_graph_beta/microsoft365_graph_beta_identity_and_access_conditional_access_policy/resource.tf, internal/resources/device_and_app_management/beta/browser_site/crud.go, internal/resources/device_and_app_management/beta/browser_site_list/crud.go, internal/resources/device_and_app_management/beta/m365_apps_installation_options/crud.go, internal/resources/device_and_app_management/beta/macos_pkg_app/crud.go, internal/resources/device_and_app_management/beta/win32_lob_app/crud.go, internal/resources/device_and_app_management/beta/winget_app/crud.go, internal/resources/device_and_app_management/v1.0/cloud_pc_device_image/crud.go, internal/resources/device_and_app_management/v1.0/cloud_pc_provisioning_policy/crud.go, internal/resources/device_and_app_management/v1.0/cloud_pc_user_setting/crud.go, internal/resources/device_and_app_management/v1.0/role_definition/crud.go, internal/resources/identity_and_access/beta/conditional_access_policy/crud.go
=> fix: standardised use of object throughout crud functions

internal/resources/common/plan_modifiers/string.go, internal/resources/common/utilities/utilities.go, internal/resources/common/utilities/utilities_test.go, internal/resources/device_and_app_management/beta/winget_app/construct_resource.go, internal/resources/device_and_app_management/beta/winget_app/model.go, internal/resources/device_and_app_management/beta/winget_app/resource.go, internal/resources/device_and_app_management/beta/winget_app/state_resource.go
=> feat: added the option to manually define winget app metadata along side auto generation + plan modifers

examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_win_get_app/resource.tf, internal/resources/common/plan_modifiers/string.go, internal/resources/common/utilities/utilities.go, internal/resources/common/utilities/utilities_test.go, internal/resources/device_and_app_management/beta/assignment_filter/state.go, internal/resources/device_and_app_management/beta/winget_app/construct_resource.go, internal/resources/device_and_app_management/beta/winget_app/crud.go, internal/resources/device_and_app_management/beta/winget_app/model.go, internal/resources/device_and_app_management/beta/winget_app/resource.go, internal/resources/device_and_app_management/beta/winget_app/state_resource.go
=> fix: updated docs

internal/resources/common/constructors/beta/device_and_app_management/mobile_app_assignment.go, internal/resources/common/shared_models/graph_beta/device_and_app_management/mobile_app_assignments.go, internal/resources/device_and_app_management/beta/winget_app/crud.go, internal/resources/device_and_app_management/beta/winget_app/model.go, internal/resources/device_and_app_management/beta/winget_app/resource.go, internal/resources/device_and_app_management/beta/winget_app/state_assignment.go
=> fix: for constructAssignmentTarget within mobile app assignments

internal/datasources/device_and_app_management/graph_beta/assignment_filter/read.go, internal/datasources/device_and_app_management/graph_beta/macos_platform_script/read.go, internal/datasources/device_and_app_management/graph_beta/role_scope_tag/read.go, internal/datasources/device_and_app_management/graph_beta/windows_platform_script/read.go, internal/datasources/device_and_app_management/graph_v1.0/cloud_pc_device_image/read.go
… to use graph_beta and graph_v1.0
=> fix: update import paths for device and app management resource to use graph_beta and graph_v1.0

docs/resources/graph_beta_device_and_app_management_win_get_app.md, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_win_get_app/resource.tf, internal/resources/common/validators/graph_beta/device_and_app_management/mobile_app_assignment.go
=> feat: implement validation for mobile app assignment settings and restart timing relationships

examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_win_get_app/resource.tf, internal/resources/common/state/type_conversion.go, internal/resources/common/validators/graph_beta/device_and_app_management/mobile_app_assignment.go, internal/resources/device_and_app_management/graph_beta/winget_app/state_assignment.go
=> feat: add StringListToTypeList function for converting string slices

internal/resources/device_and_app_management/graph_beta/winget_app/state_assignment.go
=> fix: added function comments for mobile app assignments

docs/resources/graph_beta_device_and_app_management_settings_catalog_template.md, internal/resources/device_and_app_management/graph_beta/settings_catalog_template/resource.go
=> docs: update example settings for device and app management templates

docs/resources/graph_beta_device_and_app_management_settings_catalog_template.md, internal/resources/device_and_app_management/graph_beta/settings_catalog_template/construct_resource.go, internal/resources/device_and_app_management/graph_beta/settings_catalog_template/resource.go
=> feat: added all remaining settings catalog templates for Intune Endpoint security

examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_macos_pkg_app/datasource.tf, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_macos_pkg_app/import.sh, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_macos_pkg_app/resource.tf, internal/datasources/device_and_app_management/graph_beta/application_category/datasource.go, internal/datasources/device_and_app_management/graph_beta/application_category/read.go, internal/datasources/device_and_app_management/graph_beta/assignment_filter/datasource.go, internal/datasources/device_and_app_management/graph_beta/assignment_filter/read.go, internal/datasources/device_and_app_management/graph_beta/device_category/datasource.go, internal/datasources/device_and_app_management/graph_beta/device_category/read.go, internal/datasources/device_and_app_management/graph_beta/macos_pkg_app/datasource.go, internal/datasources/device_and_app_management/graph_beta/macos_pkg_app/read.go, internal/datasources/device_and_app_management/graph_beta/macos_platform_script/datasource.go, internal/datasources/device_and_app_management/graph_beta/macos_platform_script/read.go, internal/datasources/device_and_app_management/graph_beta/reuseable_policy_settings/datasource.go, internal/datasources/device_and_app_management/graph_beta/reuseable_policy_settings/read.go, internal/datasources/device_and_app_management/graph_beta/role_scope_tag/datasource.go, internal/datasources/device_and_app_management/graph_beta/role_scope_tag/read.go, internal/datasources/device_and_app_management/graph_beta/windows_platform_script/datasource.go, internal/datasources/device_and_app_management/graph_beta/windows_platform_script/read.go, internal/provider/datasources.go, internal/resources/device_and_app_management/graph_beta/macos_pkg_app/model.go, templates/data-sources/graph_beta_device_and_app_management_macos_pkg_app.md.tmpl
=> Feat: added timeouts to datasources

.github/workflows/go-lint.yml, .github/workflows/linter.yml.testing
=> testing go lint

.github/workflows/generate-docs.yml, .github/workflows/go-lint.yml, .golangci.yml
=> fix: go-lint

internal/resources/device_management/graph_beta/device_enrollment_configuration/state.go
=> fix: for enum handling within GetDeviceEnrollmentConfigurationType

internal/resources/device_management/graph_beta/windows_remediation_script/constructor.go
=> fix fox remediation script constructor

internal/provider/client_credential_factory_test.go, internal/provider/populate_test.go, internal/provider/validate_provider_test.go
=> feat: added refactored unit tests for provider build and credential factory

.github/workflows/generate-docs.yml
=> fix: for doc gen pipeline

.github/workflows/auto-merge-dependabot.yml, .github/workflows/close-stale-issues.yml
=> fix: added close stale issues maintainence pipeline

internal/provider/resources.go, internal/resources/groups/graph_beta/group_owner_assignment/crud.go, internal/resources/groups/graph_beta/group_owner_assignment/resource.go
=> feat: added GroupOwnerAssignmentResource

README.md
=> fix: added discord info to readme

.github/workflows/tf-registry-goreleaser.yml
=> fix: increased timeout for goreleaser to 90 minutes

.github/workflows/tf-registry-goreleaser.yml
=> fix: tf-registry-goreleaser.yml permission fix

.gitignore, docs/resources/graph_beta_groups_group_member_assignment.md, docs/resources/graph_beta_identity_and_access_conditional_access_policy.md, docs/resources/graph_beta_users_user_license_assignment.md, docs/resources/graph_device_management_device_configuration_assignment.md, internal/client/build_clients.go, internal/client/build_mock_clients.go, internal/client/graph_clients.go, internal/client/http_clients.go, internal/provider/configure_clients.go, internal/services/common/convert/graph_to_framework.go, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/construct.go, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/crud.go, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/mocks/responders.go, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/mocks/terraform/resource_maximal.tf, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/mocks/terraform/resource_minimal.tf, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/resource.go, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/resource_test.go, internal/services/resources/identity_and_access/graph_beta/conditional_access_policy/state.go, templates/resources/graph_beta_groups_group.md.tmpl, templates/resources/graph_beta_groups_group_member_assignment.md.tmpl, templates/resources/graph_beta_groups_group_owner_assignment.md.tmpl, templates/resources/graph_beta_groups_license_assignment.md.tmpl, templates/resources/graph_beta_users_user.md.tmpl, templates/resources/graph_beta_users_user_license_assignment.md.tmpl, templates/resources/graph_device_management_device_configuration_assignment.md.tmpl
=> fix: numerous fixes for conditional access policies. uses a new non kiota based sdk http client

docs/resources/graph_beta_device_and_app_management_win32_lob_app.md, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_and_app_management_win32_lob_app/resource.tf
=> docs: updates for win32_lob_app docs

internal/services/resources/windows_365/graph_beta/cloud_pc_provisioning_policy/crud.go
=> fix: added assignment removal to deletion of CloudPcProvisioningPolicy resource

.github/ai-instructions.md
Add comprehensive testing infrastructure documentation to the AI instructions file to guide AI assistants and developers in understanding and using the provider's testing framework.
N/A - Documentation improvement
- Why is this change needed? The existing AI instructions lacked detailed information about the testing infrastructure, making it difficult for AI assistants and new contributors to understand the testing patterns and best practices.
- What problem does it solve? This provides clear guidance on unit vs acceptance tests, test execution commands, mock infrastructure, and testing best practices specific to this Terraform provider.
- This change improves developer onboarding and ensures consistent testing approaches across contributions.
- No new dependencies required
- No …
=> docs: add testing infrastructure documentation to AI instructions

docs/resources/graph_beta_device_management_macos_custom_attribute_script.md, docs/resources/graph_beta_device_management_macos_software_update_configuration.md, docs/resources/graph_beta_device_management_windows_remediation_script.md, docs/resources/graph_beta_device_management_windows_update_ring.md, examples/microsoft365_graph_beta/microsoft365_graph_beta_device_management_windows_update_ring/resource.tf, internal/services/resources/device_management/graph_beta/macos_custom_attribute_script/mocks/terraform/resource_maximal.tf, internal/services/resources/device_management/graph_beta/macos_custom_attribute_script/mocks/terraform/resource_minimal.tf, internal/services/resources/device_management/graph_beta/macos_software_update_configuration/mocks/terraform/resource_maximal.tf, internal/services/resources/device_management/graph_beta/macos_software_update_configuration/mocks/terraform/resource_minimal.tf, internal/services/resources/device_management/graph_beta/windows_remediation_script/mocks/terraform/resource_maximal.tf, internal/services/resources/device_management/graph_beta/windows_remediation_script/mocks/terraform/resource_minimal.tf, internal/services/resources/device_management/graph_beta/windows_update_ring/mocks/terraform/resource_maximal.tf, internal/services/resources/device_management/graph_beta/windows_update_ring/mocks/terraform/resource_minimal.tf, internal/services/resources/device_management/graph_beta/windows_update_ring_action/construct.go, internal/services/resources/device_management/graph_beta/windows_update_ring_action/crud.go, internal/services/resources/device_management/graph_beta/windows_update_ring_action/model.go, internal/services/resources/device_management/graph_beta/windows_update_ring_action/resource.go, internal/services/resources/device_management/graph_beta/windows_update_ring_action/state.go
=> chore: update docs

.github/workflows/tf-registry-goreleaser.yml
=> fix: for pipeline runner

.github/workflows/generate-docs.yml, .github/workflows/provider-release.yml, .github/workflows/tf-registry-goreleaser.yml
=> fix: release pipelines

.github/workflows/provider-release.yml
=> fix: trying with 1

internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/mocks/responders.go, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/resource_acceptance_test.go, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/resource_test.go, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/responses/validate_create/post_windows_quality_update_expedite_policy_error.json, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/responses/validate_delete/get_windows_quality_update_expedite_policy_not_found.json, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/acceptance/resource_maximal.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/acceptance/resource_minimal.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/acceptance/resource_with_assignments.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/unit/resource_maximal.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/unit/resource_minimal.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/unit/resource_with_exclusion_assignment.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy/tests/terraform/unit/resource_with_group_assignments.tf, internal/services/resources/device_management/graph_beta/windows_quality_update_policy/tests/responses/validate_create/post_windows_quality_update_policy_error.json
=> feat: added unit and acc tests for windows_quality_update_expedite_policy

.github/workflows/provider-release.yml, .github/workflows/tf-registry-goreleaser.yml
=> chore: testing runners

docs/resources/graph_beta_device_management_windows_device_compliance_policy.md, internal/constants/regex.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/construct.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/construct_device_compliance_scheduled_action_for_rules.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/crud.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/model.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/resource.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/state.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/state_assignments.go, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_custom_compliance.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_device_health.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_device_properties.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_microsoft_defender_for_endpoint.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_system_security.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_wsl.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/tests/terraform/acceptance/compliance_policy_wsl_assignments.tf, internal/services/resources/device_management/graph_beta/windows_device_compliance_policy/validate.go
=> fix: windows_device_compliance_policy refactor

go.sum
=> deps: tidy

.github/workflows/go-lint.yml, docs/guides/oidc_github.md, internal/client/client_credential_factory.go
=> fix: for github_oidc auth and updated relevant docs

README.md, docs/development/known_bugs.md, docs/development/project_status.md
=> feat: updated docs

internal/client/client_credential_factory.go, internal/provider/configure_clients.go, internal/provider/provider.go, internal/provider/set_configuration.go
=> fix: more debug logging for oidc
